version: '3.1'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file: db.env
    #environment:
    #  - MYSQL_ROOT_PASSWORD = ${MYSQL_ROOT_PASSWORD}
